### PR TITLE
Pass additional params in extract methods

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
Before we merge this we need

- sqlite caching to include this parameter
- database migration script
- migrate test database
- migrate databases used in analyses for papers

**Comment by caufieldjh** [comment]
As per discussion w/ @cmungall , will try to set this up more like passing a whole set of params directly to the API client as kwargs rather than specifying params for each. This will make it more flexible and avoid worries about which param works with which implementation, though it will mean parsing the additional args consistently (at least keeping the order the same) and updating the sqlite cache as noted above.

**Comment by caufieldjh** [comment]
See API reference: https://platform.openai.com/docs/api-reference/introduction

**Comment by caufieldjh** [comment]
The `llm` package handles this (i.e., passing model params) well, so in the interest of not reinventing any wheels I will try to implement passing params in the course of implementing `llm`. See #143 

Will still need to do some work to update openai api sqlite cache

**Pull request closed without merging**
