### PR TITLE
Fixes for the BC5CDR evaluation

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Comment by caufieldjh** [comment]
This will still need some checks to ensure the results are getting compared to the test set as expected.
Example output for one test object:
```
  - test_object:
      publication:
        id: '254'
        title: Hepatitis and renal tubular acidosis after anesthesia with methoxyflurane.
        abstract: A 69-year-old man operated for acute cholecystitis under methoxyflurane
          anesthesia developed postoperatively a hepatic insufficiency syndrome and
          renal tubular acidosis. Massive bleeding appeared during surgery which lasted
          for six hours. Postoperative evolution under supportive therapy was favourable.
          Complete recovery was confirmed by repeated controls performed over a period
          of one year after surgery.
        combined_text: N/A
        full_text: N/A
      triples:
        - subject: MESH:D008733
          predicate: induces
          object: MESH:D000141
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: induces
          object: MESH:D056486
          qualifier:
          subject_qualifier:
          object_qualifier:
    true_positives:
      -   - MESH:D008733 Methoxyflurane
          - MESH:D000141 Acidosis, Renal Tubular
      -   - MESH:D008733 Methoxyflurane
          - MESH:D056486 Chemical and Drug Induced Liver Injury
    num_true_positives: 2
    false_positives:
      -   - MESH:D008733 Methoxyflurane
          - MESH:D017093 Liver Failure
    num_false_positives: 1
    false_negatives: []
    num_false_negatives: 0
    scores:
      similarity:
        jaccard: 0.75
        false_positives:
          - MESH:D017093 Liver Failure
        false_negatives: []
        common:
          - MESH:D000141 Acidosis, Renal Tubular
          - MESH:D008733 Methoxyflurane
          - MESH:D056486 Chemical and Drug Induced Liver Injury
    predicted_object:
      publication:
      triples:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D056486
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D000141
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D056486
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D000141
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D056486
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D000141
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D017093
          qualifier:
          subject_qualifier:
          object_qualifier:
        - subject: MESH:D008733
          predicate: INDUCES
          object: MESH:D000141
          qualifier:
          subject_qualifier:
          object_qualifier:
    named_entities:
      - id: MESH:D008733
        label: Methoxyflurane
      - id: MESH:D056486
        label: Hepatitis
      - id: MESH:D000141
        label: renal tubular acidosis
      - id: MESH:D008733
        label: Methoxyflurane
      - id: MESH:D056486
        label: Hepatitis
      - id: MESH:D000141
        label: renal tubular acidosis
      - id: MESH:D008733
        label: Methoxyflurane
      - id: MESH:D056486
        label: Hepatitis
      - id: MESH:D000141
        label: renal tubular acidosis
      - id: MESH:D008733
        label: Methoxyflurane
      - id: MESH:D056486
        label: Hepatitis
      - id: MESH:D000141
        label: renal tubular acidosis
      - id: MESH:D017093
        label: hepatic insufficiency syndrome
```

**Comment by cmungall** [comment]
I see a list of lists under TPs and FPs. That is very suspect. We didn't
have that schema before. It makes me thing there is an `add` happening in
place of `extend`

**Comment by caufieldjh** [comment]
> I see a list of lists under TPs and FPs. That is very suspect. We didn't
> have that schema before. It makes me thing there is an `add` happening in
> place of `extend`

I think that's because they're lists of tuples, and in the ctd-run-2023-01-01 output they looked like this because the :
```
  true_positives:
  - !!python/tuple
    - MESH:D019386 Alendronate
    - MESH:D010146 Pain
  num_true_positives: 1
  false_positives:
  - !!python/tuple
    - MESH:D019386 Alendronate
    - MESH:D059352 Musculoskeletal Pain
```

Still looks strange, though it looks like the pairs are getting compared to test appropriately.

**Comment by cmungall** [comment]
ah that makes sense. Everything looks in order then

**Pull request merged**
