### PR TITLE
add azure openai api support to ontogpt

### PR DESCRIPTION
**Pull request by k-bandi**
This PR adds support for using Azure OpenAI API endpoints in OntoGPT for the LLM component instead of Vanilla OpenAI endpoints.

### CODE REVIEW

**Comment by caufieldjh** [comment]
Thanks @k-bandi !
I will make some updates to this to ensure we retain the base functionality, but Azure support is certainly appreciated!

**Comment by k-bandi** [comment]
@caufieldjh - Thank you. Should I close this PR now?

**Comment by caufieldjh** [comment]
Please leave it open! I'm very happy to have your contribution and would like to integrate it.

**Comment by k-bandi** [comment]
Okay great. Thank you. Let me know if you need anything.

**Comment by caufieldjh** [comment]
Just getting back to this now - thanks for your patience @k-bandi. Should be able to get it working and merged today.

**Comment by caufieldjh** [comment]
OK, this should be ready to use! Two notes:
* There is now a CLI flag named `--azure-select`. Use this with a command like `extract` to use an Azure endpoint, though it will still expect the configuration details to be defined in a local.toml.
* I'm going to be refactoring OntoGPT more soon to reduce the amount of model changes we have to track in this project (i.e., we'll let other packages like `llm` and `litellm` do that) but will try to keep that CLI flag as it's a useful shorthand. This may mean that the process for storing model configurations will change, however.
* I don't have an Azure endpoint to test with, so I'm making some assumptions about how well this works. Please let me know if it is broken or doesn't work as expected!

**Comment by k-bandi** [comment]
Thanks @caufieldjh for looking into this.

**Pull request merged**
