### PR TITLE
Generalize ibd template to disease_physiology

### PR DESCRIPTION
**Pull request by justaddcoffee**
Per convo with @cmungall @caufieldjh, generalize ibd template to disease_physiology

### CODE REVIEW

**Comment by justaddcoffee** [comment]
Can @cmungall or @caufieldjh help? When I run 

`ontogpt extract -t disease_physiology.DiseasePhysiologyAnnotations PMC6386158_fig2_legend.txt`

I see this error:

```
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for DiseasePhysiologyAnnotations
activities
  extra fields not permitted (type=value_error.extra)
```

But I don't really know where in the pydantic model the problem is

DiseasePhysiologyAnnotations activities looks like this: 

```
      activities:
        description: semicolon-separated list of molecular activities
        multivalued: true
        range: MolecularActivity
```

What extra fields is pydantic complaining about?

**Comment by caufieldjh** [comment]
There's inconsistency between your pydantic classes and the YAML - rebuild the py and it should work

**Comment by justaddcoffee** [comment]
Thanks @caufieldjh - how do I rebuild the py? 

I think that the output you are seeing is PMC6386158_fig2_legend.txt being interpreted as a string?

**Comment by caufieldjh** [comment]
Try `make src/ontogpt/templates/disease_physiology.py` to rebuild

You're right, that's the issue with input parsing.

**Comment by cmungall** [comment]
that's a lot of N/As! Next I would look at the prompt being generated there must be something off there

**Comment by justaddcoffee** [comment]
> that's a lot of N/As! Next I would look at the prompt being generated there must be something off there


@caufieldjh @cmungall I think this is an example of [this issue](https://github.com/monarch-initiative/ontogpt/issues/55) - we maybe should change parsing of text input to disambiguate text coming from a file from text coming directly from stdin

**Comment by justaddcoffee** [comment]
> There's inconsistency between your pydantic classes and the YAML - rebuild the py and it should work

@caufieldjh you were right, it was inconsistency between the pydantic class and YAML - however, the issue was that I had deleted this block:

```
    activities: Optional[List[str]] = Field(
        default_factory=list, description="""semicolon-separated list of molecular activities"""
    )
```

so activities wasn't in DiseasePhysiologyAnnotations at all

**Comment by justaddcoffee** [comment]
closed in favor of #120

**Pull request closed without merging**
