### PR TITLE
Retrieve remote models for local use and pass extract prompt to them

### PR DESCRIPTION
**Pull request by caufieldjh**
This PR adds retrieval of GGML models (specifically, the GPT4All models) for local use - they are retrieved with pystow/requests.
The same process may be used for other models named in ~~models.py~~ models.yaml.

~~That models.py may be more convenient to reference as TSV or YAML. It's python for now to make importing the model metadata easier.~~ Done, it's a YAML

### CODE REVIEW

**Comment by caufieldjh** [comment]
This will be broken until I set up the model runner in `gpt4all_runner.py` to take inputs like the OpenAI API does

**Comment by caufieldjh** [comment]
This needs some tests and a catch for the issue below and I'll call it done.

Some prompt + model combinations won't have enough memory to work with when using default parameters:
```
$ ontogpt --verbose extract -t gocam.GoCamAnnotations -i gocam-betacat.txt -m ggml-gpt4all-j-v1.3-groovy
...
gptj_model_load: loading model from '/home/harry/.data/ontogpt/ggml-gpt4all-j-v1.3-groovy.bin' - please wait ...
gptj_model_load: n_vocab = 50400
gptj_model_load: n_ctx   = 2048
gptj_model_load: n_embd  = 4096
gptj_model_load: n_head  = 16
gptj_model_load: n_layer = 28
gptj_model_load: n_rot   = 64
gptj_model_load: f16     = 2
gptj_model_load: ggml ctx size = 4505.45 MB
gptj_model_load: memory_size =   896.00 MB, n_mem = 57344
gptj_model_load: ................................... done
gptj_model_load: model size =  3609.38 MB / num tensors = 285
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 15415932800, available 15408349008)
```

It's not immediately clear to me how to address this through langchain; see https://github.com/imartinez/privateGPT/issues/104

**Comment by caufieldjh** [comment]
Ah, also needs to adjust the backend langchain uses for each model (for now it assumes the model is gpt-j like)

**Comment by caufieldjh** [comment]
Loading LLAMA/Alpaca/Vicuna models through Langchain depends on `llama.cpp`, and that updates frequently, which may or may not be related to errors like this:
```
llama_model_load: loading model from '/home/harry/.data/ontogpt/ggml-stable-vicuna-13B.q4_2.bin' - please wait ...
llama_model_load: n_vocab = 32001
llama_model_load: n_ctx   = 512
llama_model_load: n_embd  = 5120
llama_model_load: n_mult  = 256
llama_model_load: n_head  = 40
llama_model_load: n_layer = 40
llama_model_load: n_rot   = 128
llama_model_load: f16     = 5
llama_model_load: n_ff    = 13824
llama_model_load: n_parts = 2
llama_model_load: type    = 2
llama_model_load: invalid model file '/home/harry/.data/ontogpt/ggml-stable-vicuna-13B.q4_2.bin' (bad f16 value 5)
llama_init_from_file: failed to load model
Segmentation fault
```

**Comment by caufieldjh** [comment]
This will take a few more iterations to get OpenAI-like results but it's a start.

**Comment by caufieldjh** [comment]
For each of the GPT4ALL models:
* ggml-gpt4all-j-v1.3-groovy - loads w/o errors. Generates text relevant to the prompt but rarely follows instructions.
* ggml-gpt4all-l13b-snoozy - langchain returns `Invalid model file` error. Possibly due to changes in `llama.cpp` so see https://github.com/ggerganov/llama.cpp/issues/662
* ggml-mpt-7b-chat - loads w/o errors. Generated text appears to truncate early (e.g., results like `' name: Sl'`)
* ggml-mpt-7b-instruct - loads w/o errors. Gets rather creative with formatting and hallucination (e.g., it suggested that one of the symptoms of Sly syndrome is "Noonan syndrome-like facial dysmorphia" which isn't exactly true, though both syndromes involve facial appearance)
* ggml-stable-vicuna-13B.q4_2 - as with ggml-gpt4all-l13b-snoozy, raises `Invalid model file` error.
* ggml-wizardLM-7B.q4_2 - also `Invalid model file` error

**Comment by caufieldjh** [comment]
See re: the models failing to load: https://github.com/nomic-ai/gpt4all/issues/866

**Review by cmungall — APPROVED** [review]

**Pull request merged**
