### PR TITLE
Run mypy through tox and address type check errors

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Comment by caufieldjh** [comment]
The full error list is >500 items, so for readability it's here:
https://pastebin.com/HRstXAKg

**Comment by caufieldjh** [comment]
Probably want to ignore templates for now - this is apparently more complicated with mypy than I thought, as 
```
tox -e mypy -- --exclude '/src/ontogpt/templates/*'
```
does not do it, even with the `--follow-imports skip` option added

**Comment by caufieldjh** [comment]
Templates are technically excluded from mypy scanning, but will still show up with errors if something else imports them.

**Comment by caufieldjh** [comment]
Now ignoring templates, but see also https://github.com/linkml/linkml/issues/1632

**Comment by caufieldjh** [comment]
Will ignore scripts like the gpt4all_engine as the plan is still to combine with other classes+functions to reduce redundancy

**Comment by caufieldjh** [comment]
That should be it for the type fixes - a bit more cleanup and this one is ready

**Review by cmungall — APPROVED** [review]

**Comment by caufieldjh** [comment]
Failing tests:
* tests.unit.test_converters.test_ontology_converter (TypeError: non-default argument 'adapter' follows default argument)
* tests.unit.test_unit_cli (TypeError: non-default argument 'adapter' follows default argument)
* test_load_gene_sets (ValueError: Unknown format)
* test_populate (ValueError: Unknown format)

**Pull request merged**
