### PR TITLE
Implement llm api

### PR DESCRIPTION
**Pull request by caufieldjh**
This one, specifically https://github.com/simonw/llm

### CODE REVIEW

**Comment by caufieldjh** [comment]
Set linkml-runtime to [.6.0rc2](https://pypi.org/project/linkml-runtime/1.6.0rc2/) for the pydantic compatibility

**Comment by caufieldjh** [comment]
The bioregistry dependency in oaklib becomes relevant here:
```
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 3, in <module>
    from ontogpt.cli import main
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 17, in <module>
    from oaklib import get_adapter
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/__init__.py", line 9, in <module>
    from oaklib.selector import get_adapter, get_implementation_from_shorthand  # noqa:F401
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/selector.py", line 15, in <module>
    from oaklib.implementations.funowl.funowl_implementation import FunOwlImplementation
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/implementations/__init__.py", line 13, in <module>
    from oaklib.implementations.cx.cx_implementation import CXImplementation
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/implementations/cx/cx_implementation.py", line 9, in <module>
    from oaklib.implementations.obograph.obograph_implementation import (
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/implementations/obograph/obograph_implementation.py", line 41, in <module>
    from oaklib.interfaces.differ_interface import DifferInterface
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/interfaces/differ_interface.py", line 25, in <module>
    from oaklib.utilities.kgcl_utilities import generate_change_id
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/oaklib/utilities/kgcl_utilities.py", line 11, in <module>
    import kgcl_schema.grammar.parser as kgcl_parser
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/kgcl_schema/grammar/parser.py", line 9, in <module>
    from bioregistry import parse_iri, get_preferred_prefix, curie_to_str
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/bioregistry/__init__.py", line 5, in <module>
    from .collection_api import get_collection, get_context  # noqa:F401
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/bioregistry/collection_api.py", line 7, in <module>
    from .resource_manager import manager
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/bioregistry/resource_manager.py", line 36, in <module>
    from .schema import (
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/bioregistry/schema/__init__.py", line 5, in <module>
    from .struct import (  # noqa:F401
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/bioregistry/schema/struct.py", line 35, in <module>
    from bioregistry.utils import curie_to_str, deduplicate, removeprefix, removesuffix
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/bioregistry/utils.py", line 25, in <module>
    from pydantic.json import ENCODERS_BY_TYPE
ImportError: cannot import name 'ENCODERS_BY_TYPE' from 'pydantic.json' (/home/harry/ontogpt/.venv/lib/python3.9/site-packages/pydantic/json.py)
```

I fixed this locally by hotpatching import `pydantic` to import `pydantic.v1` in bioregistry.utils and bioregistry.schema.struct, as well as in linkml_renderer.style.model. In ontogpt I'm just going to update to whatever pydantic 2 needs.

**Comment by cmungall** [comment]
maybe be easier to see if we can get llm to work with v1 as it's going to take a wee while for our transitive dependencies to be fixed

**Comment by caufieldjh** [comment]
Output isn't getting produced in something yaml-translatable:
```
$ ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt -m orca-mini-3b
Traceback (most recent call last):                                                                                                                                                        
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 306, in extract
    write_extraction(results, output, output_format, ke)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 105, in write_extraction
    output.write(dump_minimal_yaml(results))
  File "/home/harry/ontogpt/src/ontogpt/io/yaml_wrapper.py", line 50, in dump_minimal_yaml
    yaml.dump(eliminate_empty(obj, not minimize), file)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/ruamel/yaml/main.py", line 567, in dump
    return self.dump_all([data], stream, transform=transform)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/ruamel/yaml/main.py", line 577, in dump_all
    self._context_manager.dump(data)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/ruamel/yaml/main.py", line 913, in dump
    self._yaml.representer.represent(data)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/ruamel/yaml/representer.py", line 81, in represent
    node = self.represent_data(data)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/ruamel/yaml/representer.py", line 113, in represent_data
    node = self.yaml_representers[None](self, data)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/ruamel/yaml/representer.py", line 345, in represent_undefined
    raise RepresenterError(f'cannot represent an object: {data!s}')
ruamel.yaml.representer.RepresenterError: cannot represent an object: input_id=None input_title=None input_text='Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.\n' raw_completion_output=' name: Sly syndrome\ndescription: Autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme ��-glucuronidase\nsynonyms: MPS-VII, mucopolysaccharidosis type VII\nsubclass_of: None (it is not a genetic disorder)\nsymptoms: Buildup in many tissues and organs of the body due to a lack of enzyme ��-glucuronidase\ninheritance: Autosomal recessive\ngenes: PEX1, PEX2, PEX3\ndisease_onsets: Adult; juvenile; first decade\nlabel: The label (name) of the named thing' prompt='From the text below, extract the following entities in the following format:\n\nname: <the name of the disease>\ndescription: <a description of the disease>\nsynonyms: <semicolon-separated list of synonymss>\nsubclass_of: <semicolon-separated list of subclass_ofs>\nsymptoms: <semicolon-separated list of symptomss>\ninheritance: <the value for inheritance>\ngenes: <semicolon separated list of gene symbols; for example: PEX1; PEX2; PEX3>\ndisease_onsets: <semi-colon separated list of onsets at which the disease occurs, for example: adult; juvenile; first decade>\nlabel: <The label (name) of the named thing>\n\n\nText:\nSly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.\n\n\n===\n\n' extracted_object=MendelianDisease(id=None, label='The label (name) of the named thing', name='Sly syndrome', description='Autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme ��-glucuronidase', synonyms=['MPS-VII, mucopolysaccharidosis type VII'], subclass_of=['AUTO:None%20%28it%20is%20not%20a%20genetic%20disorder%29'], symptoms=['AUTO:Buildup%20in%20many%20tissues%20and%20organs%20of%20the%20body%20due%20to%20a%20lack%20of%20enzyme%20%EF%BF%BD%EF%BF%BD-glucuronidase'], inheritance='HP:0000007', genes=['AUTO:PEX1%2C%20PEX2%2C%20PEX3'], disease_onsets=['AUTO:Adult', 'AUTO:juvenile', 'AUTO:first%20decade'], publications=[]) named_entities=[NamedEntity(id='AUTO:None%20%28it%20is%20not%20a%20genetic%20disorder%29', label='None (it is not a genetic disorder)'), NamedEntity(id='AUTO:Buildup%20in%20many%20tissues%20and%20organs%20of%20the%20body%20due%20to%20a%20lack%20of%20enzyme%20%EF%BF%BD%EF%BF%BD-glucuronidase', label='Buildup in many tissues and organs of the body due to a lack of enzyme ��-glucuronidase'), NamedEntity(id='HP:0000007', label='Autosomal recessive'), NamedEntity(id='AUTO:PEX1%2C%20PEX2%2C%20PEX3', label='PEX1, PEX2, PEX3'), NamedEntity(id='AUTO:Adult', label='Adult'), NamedEntity(id='AUTO:juvenile', label='juvenile'), NamedEntity(id='AUTO:first%20decade', label='first decade')]
```

**Comment by caufieldjh** [comment]
This generally works, though it's a bit slow for the larger models (another case of being spoiled by GPT).
Example:
```
$ time ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt -m ggml-wizardLM-7B
input_text: |
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.
raw_completion_output: |-
  name: Sly syndrome
  description: An autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase, which is responsible for breaking down large sugar molecules called glycosaminoglycans (GAGs).
  synonyms: ;
  subclass_of: Lysosomal Storage Disorders
  symptoms: Increased tissue and organ GAG buildup; progressive physical and mental development delay, including intellectual disability, seizures, and vision and hearing loss.
  inheritance: Autosomal recessive
  genes: PEX1, PEX2, PEX3 (for the enzyme β-glucuronidase)
  disease_onsets: Adult; juvenile; first decade
  label: Sly syndrome
prompt: |+
  From the text below, extract the following entities in the following format:

  name: <the name of the disease>
  description: <a description of the disease>
  synonyms: <semicolon-separated list of synonymss>
  subclass_of: <semicolon-separated list of subclass_ofs>
  symptoms: <semicolon-separated list of symptomss>
  inheritance: <the value for inheritance>
  genes: <semicolon separated list of gene symbols; for example: PEX1; PEX2; PEX3>
  disease_onsets: <semi-colon separated list of onsets at which the disease occurs, for example: adult; juvenile; first decade>
  label: <The label (name) of the named thing>


  Text:
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.


  ===

extracted_object:
  label: Sly syndrome
  name: Sly syndrome
  description: An autosomal recessive lysosomal storage disease caused by a deficiency
    of the enzyme β-glucuronidase, which is responsible for breaking down large sugar
    molecules called glycosaminoglycans (GAGs).
  subclass_of:
    - MONDO:0002561
  symptoms:
    - AUTO:Increased%20tissue%20and%20organ%20GAG%20buildup
    - AUTO:progressive%20physical%20and%20mental%20development%20delay%2C%20including%20intellectual%20disability%2C%20seizures%2C%20and%20vision%20and%20hearing%20loss.
  inheritance: HP:0000007
  genes:
    - AUTO:PEX1%2C%20PEX2%2C%20PEX3%20%28for%20the%20enzyme%20%CE%B2-glucuronidase%29
  disease_onsets:
    - AUTO:Adult
    - AUTO:juvenile
    - AUTO:first%20decade
named_entities:
  - id: MONDO:0002561
    label: Lysosomal Storage Disorders
  - id: AUTO:Increased%20tissue%20and%20organ%20GAG%20buildup
    label: Increased tissue and organ GAG buildup
  - id: 
      AUTO:progressive%20physical%20and%20mental%20development%20delay%2C%20including%20intellectual%20disability%2C%20seizures%2C%20and%20vision%20and%20hearing%20loss.
    label: progressive physical and mental development delay, including intellectual
      disability, seizures, and vision and hearing loss.
  - id: HP:0000007
    label: Autosomal recessive
  - id: AUTO:PEX1%2C%20PEX2%2C%20PEX3%20%28for%20the%20enzyme%20%CE%B2-glucuronidase%29
    label: PEX1, PEX2, PEX3 (for the enzyme β-glucuronidase)
  - id: AUTO:Adult
    label: Adult
  - id: AUTO:juvenile
    label: juvenile
  - id: AUTO:first%20decade
    label: first decade

real    2m52.024s
user    9m48.402s
sys     0m5.555s
```

**Comment by caufieldjh** [comment]
Tests won't clear for pydantic reasons

**Comment by caufieldjh** [comment]
ggml-mpt-7b-instruct results are disappointing - example:
```
$ time ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt -m ggml-mpt-7b-instruct
ERROR:root:Cannot find slot for here_are_some_facts_about_slosky_syndrome,_also_called_mucopolysaccharidosis_type_vii_(mps-vii) in Here are some facts about Slosky syndrome, also called Mucopolysaccharidosis type VII (MPS-VII):
ERROR:root:Line '1.  It is an autosomal recessive lysosomal storage disorder caused by a deficiency in beta glucuronidase enzyme which breaks down large sugar molecules known as glycosaminoglycans or mucopoly saccharides' does not contain a colon; ignoring
ERROR:root:Cannot ground None annotation, cls=MendelianDisease

real    1m55.216s
user    6m44.795s
sys     0m11.021s
```

**Comment by caufieldjh** [comment]
llama-2-7b-chat is, unsurprisingly, chatty:
```
$ time ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt -m llama-2-7b-chat
ERROR:root:Cannot find slot for sure!_here_is_the_information_you_requested_for_sly_syndrome in Sure! Here is the information you requested for Sly syndrome:
ERROR:root:Cannot find slot for gene(s) in Gene(s): PEX1; PEX2; PEX3
ERROR:root:Cannot find slot for disease_onset in Disease onset: Adult, juvenile, first decade
input_text: |
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.
raw_completion_output: |2-
   Sure! Here is the information you requested for Sly syndrome:
  Name: Sly syndrome, Mucopolysaccharidosis type VII (MPS-VII)
  Description: An autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (GAGs or mucopolysaccharides).
  Synonyms: MPS VII, Sly syndrome
  Subclass of: Lysosomal storage diseases
  Symptoms: The severity of the disease can vary widely and may include: Coarse facial features, short stature, joint stiffness, progressive neurological decline, corneal clouding, hearing loss, cardiovascular problems.
  Inheritance: Autosomal recessive
  Gene(s): PEX1; PEX2; PEX3
  Disease onset: Adult, juvenile, first decade
  Label: Sly syndrome
prompt: |+
  From the text below, extract the following entities in the following format:

  name: <the name of the disease>
  description: <a description of the disease>
  synonyms: <semicolon-separated list of synonymss>
  subclass_of: <semicolon-separated list of subclass_ofs>
  symptoms: <semicolon-separated list of symptomss>
  inheritance: <the value for inheritance>
  genes: <semicolon separated list of gene symbols; for example: PEX1; PEX2; PEX3>
  disease_onsets: <semi-colon separated list of onsets at which the disease occurs, for example: adult; juvenile; first decade>
  label: <The label (name) of the named thing>


  Text:
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.


  ===

extracted_object:
  label: Sly syndrome
  name: Sly syndrome, Mucopolysaccharidosis type VII (MPS-VII)
  description: An autosomal recessive lysosomal storage disease caused by a deficiency
    of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large
    sugar molecules called glycosaminoglycans (GAGs or mucopolysaccharides).
  synonyms:
    - MPS VII, Sly syndrome
  subclass_of:
    - MONDO:0002561
  symptoms:
    - AUTO:The%20severity%20of%20the%20disease%20can%20vary%20widely%20and%20may%20include%3A%20Coarse%20facial%20features%2C%20short%20stature%2C%20joint%20stiffness%2C%20progressive%20neurological%20decline%2C%20corneal%20clouding%2C%20hearing%20loss%2C%20cardiovascular%20problems.
  inheritance: HP:0000007
named_entities:
  - id: MONDO:0002561
    label: Lysosomal storage diseases
  - id: 
      AUTO:The%20severity%20of%20the%20disease%20can%20vary%20widely%20and%20may%20include%3A%20Coarse%20facial%20features%2C%20short%20stature%2C%20joint%20stiffness%2C%20progressive%20neurological%20decline%2C%20corneal%20clouding%2C%20hearing%20loss%2C%20cardiovascular%20problems.
    label: 'The severity of the disease can vary widely and may include: Coarse facial
      features, short stature, joint stiffness, progressive neurological decline,
      corneal clouding, hearing loss, cardiovascular problems.'
  - id: HP:0000007
    label: Autosomal recessive

real    2m22.369s
user    9m9.981s
sys     0m2.193s
```

**Comment by caufieldjh** [comment]
nous-hermed-13b seems to get the closest to GPT-3.5:
```
$ time ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt -m nous-hermes-13b
input_text: |
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.
raw_completion_output: |-
  name: Sly syndrome
  description: An autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase, leading to a buildup in many tissues and organs.
  synonyms: MPS VII; mucopolysaccharidosis type VII
  subclass_of: Lysosomal storage disease
  symptoms: Variable severity depending on the individual case
  inheritance: Autosomal recessive
  genes: PEX1, PEX2, PEX3
  disease_onsets: Adult, juvenile, first decade
  label: Sly syndrome
prompt: |+
  From the text below, extract the following entities in the following format:

  name: <the name of the disease>
  description: <a description of the disease>
  synonyms: <semicolon-separated list of synonymss>
  subclass_of: <semicolon-separated list of subclass_ofs>
  symptoms: <semicolon-separated list of symptomss>
  inheritance: <the value for inheritance>
  genes: <semicolon separated list of gene symbols; for example: PEX1; PEX2; PEX3>
  disease_onsets: <semi-colon separated list of onsets at which the disease occurs, for example: adult; juvenile; first decade>
  label: <The label (name) of the named thing>


  Text:
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.


  ===

extracted_object:
  label: Sly syndrome
  name: Sly syndrome
  description: An autosomal recessive lysosomal storage disease caused by a deficiency
    of the enzyme β-glucuronidase, leading to a buildup in many tissues and organs.
  synonyms:
    - MPS VII
    - mucopolysaccharidosis type VII
  subclass_of:
    - MONDO:0002561
  symptoms:
    - AUTO:Variable%20severity%20depending%20on%20the%20individual%20case
  inheritance: HP:0000007
  genes:
    - AUTO:PEX1%2C%20PEX2%2C%20PEX3
  disease_onsets:
    - AUTO:Adult%2C%20juvenile%2C%20first%20decade
named_entities:
  - id: MONDO:0002561
    label: Lysosomal storage disease
  - id: AUTO:Variable%20severity%20depending%20on%20the%20individual%20case
    label: Variable severity depending on the individual case
  - id: HP:0000007
    label: Autosomal recessive
  - id: AUTO:PEX1%2C%20PEX2%2C%20PEX3
    label: PEX1, PEX2, PEX3
  - id: AUTO:Adult%2C%20juvenile%2C%20first%20decade
    label: Adult, juvenile, first decade

real    3m24.558s
user    12m11.021s
sys     0m5.857s
```

Still tries to fill in the blanks when there aren't obvious matches.

**Comment by caufieldjh** [comment]
hrm, broke the default behavior in the meantime:
```
$ time ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 298, in extract
    results = ke.extract_from_text(text, target_class_def)
  File "/home/harry/ontogpt/src/ontogpt/engines/spires_engine.py", line 91, in extract_from_text
    extracted_object = self.parse_completion_payload(raw_text, cls, object=object)
  File "/home/harry/ontogpt/src/ontogpt/engines/spires_engine.py", line 529, in parse_completion_payload
    self._auto_add_ids(raw, cls)
  File "/home/harry/ontogpt/src/ontogpt/engines/spires_engine.py", line 542, in _auto_add_ids
    if slot.range == "uriorcurie" or self.range == "uri":
AttributeError: 'SPIRESEngine' object has no attribute 'range'
```

**Comment by caufieldjh** [comment]
Oh, `_auto_add_ids` is from #166 so that must have come in when I pulled main.

**Comment by caufieldjh** [comment]
GPT-3.5 for comparison:
```
$ time ontogpt extract -t mendelian_disease.MendelianDisease -i tests/input/cases/mendelian-disease-sly.txt
input_text: |
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.
raw_completion_output: |-
  name: Sly syndrome
  description: Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.
  synonyms: MPS-VII
  subclass_of: 
  symptoms: 
  inheritance: autosomal recessive
  genes: 
  disease_onsets: 
  label: Sly syndrome
prompt: |+
  From the text below, extract the following entities in the following format:

  name: <the name of the disease>
  description: <a description of the disease>
  synonyms: <semicolon-separated list of synonymss>
  subclass_of: <semicolon-separated list of subclass_ofs>
  symptoms: <semicolon-separated list of symptomss>
  inheritance: <the value for inheritance>
  genes: <semicolon separated list of gene symbols; for example: PEX1; PEX2; PEX3>
  disease_onsets: <semi-colon separated list of onsets at which the disease occurs, for example: adult; juvenile; first decade>
  label: <The label (name) of the named thing>


  Text:
  Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII), is an autosomal recessive lysosomal storage disease caused by a deficiency of the enzyme β-glucuronidase. This enzyme is responsible for breaking down large sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides). The inability to break down GAGs leads to a buildup in many tissues and organs of the body. The severity of the disease can vary widely.


  ===

extracted_object:
  id: 3ba050df-5355-40f5-9df0-9c83b658ae05
  label: Sly syndrome
  name: Sly syndrome
  description: Sly syndrome, also called mucopolysaccharidosis type VII (MPS-VII),
    is an autosomal recessive lysosomal storage disease caused by a deficiency of
    the enzyme β-glucuronidase. This enzyme is responsible for breaking down large
    sugar molecules called glycosaminoglycans (AKA GAGs, or mucopolysaccharides).
    The inability to break down GAGs leads to a buildup in many tissues and organs
    of the body. The severity of the disease can vary widely.
  synonyms:
    - MPS-VII
  inheritance: HP:0000007
named_entities:
  - id: HP:0000007
    label: autosomal recessive

real    0m3.697s
user    0m3.591s
sys     0m1.220s
```

**Comment by caufieldjh** [comment]
Note - remove the warning about not having a Huggingface API key if it isn't relevant. Not removing this warning may also break if calls to HF are disabled, as in this PR.

**Comment by caufieldjh** [comment]
For test and dependency compatibility purposes, pin pydantic to < 2 and revert the "pydantic.v1" changes to "pydantic" alone

**Comment by caufieldjh** [comment]
New oaklib works locally, but ontogpt also needs linkml-owl and there is a version conflict. 
See https://github.com/linkml/linkml-owl/pull/37

**Comment by caufieldjh** [comment]
Still a few bugs here, example:
```
$ ontogpt recipe-extract -m nous-hermes-13b https://www.allrecipes.com/recipe/268130/pork-and-zucchini-rice-skillet/
/home/harry/ontogpt/.venv/lib/python3.9/site-packages/mf2py/parser.py:409: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if x is not "":
/home/harry/ontogpt/.venv/lib/python3.9/site-packages/mf2py/dom_helpers.py:144: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  results = [t for t in text_collection(el, replace_img, img_to_src, base_url) if t is not '']
Traceback (most recent call last):
  File "/home/harry/ontogpt/.venv/bin/ontogpt", line 6, in <module>
    sys.exit(main())
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/harry/ontogpt/.venv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/harry/ontogpt/src/ontogpt/cli.py", line 697, in recipe_extract
    if not model:
UnboundLocalError: local variable 'model' referenced before assignment
```

**Comment by cmungall** [comment]
fwiw, llm now works with pydantic1 or 2: https://github.com/simonw/llm/releases/tag/0.8

**Pull request merged**
