### PR TITLE
Start of PR for IBD literature project

### PR DESCRIPTION
**Pull request by justaddcoffee**

### CODE REVIEW

**Comment by cmungall** [comment]
Does this replace #54?

**Comment by justaddcoffee** [comment]
Yes, I think let's start over with this (#120) pr

**Comment by caufieldjh** [comment]
The python eutils package is unfortunately incomplete (e.g., it's missing functionality for calling `epost`).
It may make sense to call the API directly through `requests`.
This example is a bit old but the general idea holds: https://gist.github.com/diallobakary4/5f5bdb702e3f0ae034a396fb2218031e
The critical details being: 
* you need to be able to pass the API key
* you need to be able to use [epost](https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.EPost)

**Comment by caufieldjh** [comment]
Issues to solve re: pubmed API:
* Rate limiting errors (429)
* Set the CLI `pubmed_annotate` to filter the PMID list *before* it returns full texts 
* Fix this:
```  File "/home/harry/ontogpt/src/ontogpt/clients/pubmed_client.py", line 367, in text
    these_docs = parse_pmxml(xml=xml_data, raw=raw, autoformat=autoformat)
  File "/home/harry/ontogpt/src/ontogpt/clients/pubmed_client.py", line 94, in parse_pmxml
    ti = pa.find("ArticleTitle").text
AttributeError: 'NoneType' object has no attribute 'text' ```

**Review by caufieldjh — APPROVED** [review]

**Pull request merged**
