### PR TITLE
first draft of biotic interaction template

### PR DESCRIPTION
**Pull request by diatomsRcool**
New template to capture biotic interactions from text - ultimately want to add to GloBI. May need to have a discussion about the annotator.

### CODE REVIEW

**Review by cmungall — CHANGES_REQUESTED** [review]
can you also add an example text?

In should be in tests/input/cases/

and the name should be `biotic_interactions-xxx.txt`

**Comment by caufieldjh** [comment]
Using the annotators that I've added here is probably excessive - ncbitaxon will capture everything and then some, while BERO is likely too broad for the kinds of things considered "biotic interactions" - so let's consider this the absolute upper bound of annotation and get more specific.

**Comment by caufieldjh** [comment]
I've been using this abstract for testing: https://pubmed.ncbi.nlm.nih.gov/26639575/
@diatomsRcool is that kind of thing in scope?

**Comment by diatomsRcool** [comment]
The only issue with NCBI is that they have identifiers only for about 25% of the known taxa. It might be ok to start with tho.

**Comment by diatomsRcool** [comment]
and yes, that PubMed abstract would be a good example of the kind of thing that is in scope

**Comment by caufieldjh** [comment]
OK, great - running
```
ontogpt pubmed-extract -t biotic_interaction.BioticInteraction 26639575
```
yields 
```
WARNING:root:Could not find any mappings for NCIT:C121660                                                                           
WARNING:root:Could not find any mappings for NCIT:C121660
input_text: 'Title: Bacteria may contribute to distant species recognition in ant-aphid
  mutualistic relationships.

 ...

raw_completion_output: "label: mutualistic relationship \nsource_taxon: ant and aphid\
  \ species \ntarget_taxon: ant and aphid species \ninteraction_type: mutualistic\
  \ interaction \n\nlabel: attraction \nsource_taxon: bacterial honeydew \ntarget_taxon:\
  \ ant \ninteraction_type: attraction \n\nlabel: discrimination \nsource_taxon: aphid\
  \ species \ntarget_taxon: ant \ninteraction_type: semiochemical-based discrimination\
  \ \n\nlabel: preference \nsource_taxon: Aphis fabae \ntarget_taxon: ant \ninteraction_type:\
  \ preference \n\nlabel: microbial influence \nsource_taxon: bacteria \ntarget_taxon:\
  \ ant and aphid species \ninteraction_type: influence"

...

extracted_object:
  label: microbial influence
  source_taxon: NCBITaxon:1869227
  target_taxon: ant and aphid species
  interaction_type: influence
named_entities:
- id: NCBITaxon:1869227
  label: bacteria
```

**Comment by diatomsRcool** [comment]
It seems to completely  miss the ant - aphid interaction

**Review by cmungall — APPROVED** [review]
The test cases should be labeled `biotic_interaction-` (not pluralized) but we can deal later

**Comment by caufieldjh** [comment]
> It seems to completely miss the ant - aphid interaction. Could that be a result of NCBI being so heavily skewed toward microbes?

I suspect ncbitaxon isn't ideal for this, yeah - maybe the taxon slim is more balanced

**Comment by caufieldjh** [comment]
It catches some ant vs. aphid interactions, just not in a way it maps to anything:
```
raw_completion_output:
	label: discrimination
	source_taxon: aphid species
	target_taxon: ant
	interaction_type: semiochemical-based discrimination

	label: preference
	source_taxon: Aphis fabae
	target_taxon: ant
	interaction_type: preference
```

**Comment by caufieldjh** [comment]
ah, found an issue on translating to pydantic:
```
$ make src/ontogpt/templates/biotic_interaction.py
poetry run gen-pydantic src/ontogpt/templates/biotic_interaction.yaml > src/ontogpt/templates/biotic_interaction.py.tmp && mv src/ontogpt/templates/biotic_interaction.py.tmp src/ontogpt/templates/biotic_interaction.py
ValueError: File "biotic_interaction.yaml", line 42, col 15: A semi-colon separated list of taxon to taxon relationships for example: Carcharodon carcharias eats elephant seal; Pandarus sinuatus parasitizes Carcharodon carcharias; orca eats Carcharodon carcharias: Not a valid NCName
make: *** [Makefile:31: src/ontogpt/templates/biotic_interaction.py] Error 1
```

**Comment by diatomsRcool** [comment]
So what was the problem?

**Comment by caufieldjh** [comment]
The prompt example needed to be under the `annotations` heading. I also split it into `prompt` for description text and `prompt.example` for the example text.

See https://github.com/monarch-initiative/ontogpt/pull/113

**Pull request merged**
