### PR TITLE
Add diagnostic_procedure template

### PR DESCRIPTION
**Pull request by caufieldjh**

### CODE REVIEW

**Review by cmungall — APPROVED** [review]

**Comment by caufieldjh** [comment]
Making progress:
```
$ ontogpt extract -t diagnostic_procedure.DiagnosticProcedureRelationship procedure2.txt
input_text: 'An elevated blood pressure measurement is associated with high blood
  pressure.

  An elevated lactate measurement in the blood is associated with lactic acidosis.

  '
raw_completion_output: "subject: Blood pressure measurement\npredicate: RELATED_TO\n\
  object: High blood pressure\nqualifier: \nsubject_qualifier: Elevated\nobject_qualifier:\
  \ High"
prompt: 'From the text below, extract the following entities in the following format:


  subject: <A diagnostic procedure yielding a result, which in turn may be interpreted
  as a phenotype. Procedures include "heart rate measurement", "blood pressure measurement",
  "oxygen saturation measurement", etc. In practice, procedures may be named based
  on what they measure, with the "measurement" part left implicit.>

  predicate: <The relationship type, e.g. RELATED_TO>

  object: <The observable physical or biochemical characteristics of a patient. Not
  equivalent to a disease state, but may contribute to a diagnosis.>

  qualifier: <A qualifier for the statements, e.g. "NOT" for negation>

  subject_qualifier: <An optional qualifier or modifier for the procedure.>

  object_qualifier: <An optional qualifier or modifier for the phenotype.>



  Text:

  An elevated blood pressure measurement is associated with high blood pressure.

  An elevated lactate measurement in the blood is associated with lactic acidosis.



  ===


  '
extracted_object:
  subject: LOINC:MTHU008342
  predicate: AUTO:RELATED_TO
  object: HP:0000822
  subject_qualifier: AUTO:Elevated
  object_qualifier: AUTO:High
named_entities:
- id: LOINC:MTHU008342
  label: Blood pressure measurement
- id: AUTO:RELATED_TO
  label: RELATED_TO
- id: HP:0000822
  label: High blood pressure
- id: AUTO:Elevated
  label: Elevated
- id: AUTO:High
  label: High
```

The CURIE `LOINC:MTHU008342` isn't from LOINC per se, but from the Bioportal version, processed from what they get from UMLS. Here it is: https://bioportal.bioontology.org/ontologies/LOINC?p=classes&conceptid=MTHU008342

**Comment by caufieldjh** [comment]
This doesn't quite work in the way I'd like yet, but I'd like to iterate on it, so will push once tests pass and work further in a new PR

**Comment by caufieldjh** [comment]
This doesn't quite do what I'd like yet - will require further iteration.
In a way, this is less a task of structuring + grounding than a model tuning issue, since the relationship between a diagnostic procedure and a phenotype can be expressed through a variety of _implicit_ ways but hypothetically consistent semantics. So perhaps it's less about text explicitly stating "Procedure X is used to determine presence of Phenotype Y" and more of procedure X just co-occurring with phenotype Y often enough. But I suspect, in practice, it may be more like procedure X with a value of (some value outside a reference range) co-occurs with phenotype Y, so the crucial detail is still that reference range

**Comment by caufieldjh** [comment]
Going to push this though to avoid further branch drift

**Pull request merged**
